query getCurrentOwnerBalances($OWNER: String!, $ASSET_TYPES: [String!]!) {
  current_fungible_asset_balances(
    where: {
_and: {owner_address: {_eq: $OWNER}, is_primary: {_eq: true},
          asset_type: {_in: $ASSET_TYPES}}}
  ) {
    owner_address
    amount
    owner_address
    asset_type
  }
}