query GetTokenIdsFromCollectionByOwner($COLLECTION: String!, $OWNER: String!) {
  current_token_datas_v2(
    where: { collection_id: { _eq: $COLLECTION }, current_token_ownerships: { owner_address: { _eq: $OWNER } }, is_deleted_v2: {_eq: false}  }
  ) {
    token_data_id
  }
}
