query GetVaultCollectionAPR($prevDebtTimestamp: timestamp!, $collectionId: String!) {
  prevDebt: vault_collection_datas(
    order_by: {transaction_version: asc},
    where: {collection_id: {_eq: $collectionId}, transaction_timestamp: {_gte: $prevDebtTimestamp}, global_debt_part: {_gt: 0}},
    limit: 1,
  ) {
    transactionTimestamp: transaction_timestamp
    transactionVersion: transaction_version
    borrowBase: borrow_base
    borrowElastic: borrow_elastic,
    globalDebt: vault_collection_debt_store_datas {
      debtBase: debt_base
      debtElastic: debt_elastic
      assetType: asset_type
    }
  }
  currentDebt: vault_collection_datas(
    order_by: {transaction_version: desc},
    where: {collection_id: {_eq: $collectionId}, global_debt_part: {_gt: 0}},
    limit: 1,
  ) {
    transactionTimestamp: transaction_timestamp
    transactionVersion: transaction_version
    borrowBase: borrow_base
    borrowElastic: borrow_elastic,
    globalDebt: vault_collection_debt_store_datas {
      debtBase: debt_base
      debtElastic: debt_elastic
      assetType: asset_type
  	}
  }
}
