query GetVaultCollectionAPR($prevDebtTimestamp: timestamp!, $collectionIds: [String!]!) {
  prevDebt: vault_collection_datas(
    order_by: [{collection_id: asc}, {transaction_version: asc}],
    where: {collection_id: {_in: $collectionIds}, transaction_timestamp: {_gte: $prevDebtTimestamp}, global_debt_part: {_gt: 0}},
    distinct_on: [collection_id]
  ) {
    collectionId: collection_id
    transactionTimestamp: transaction_timestamp
    transactionVersion: transaction_version
    borrowBase: borrow_base
    borrowElastic: borrow_elastic,
    globalDebt: vault_collection_debt_store_datas {
      debtBase: debt_base
      debtElastic: debt_elastic
      objectAddress: object_address
    }
  }
  currentDebt: vault_collection_datas(
    order_by: [{collection_id: asc}, {transaction_version: desc}],
    where: {collection_id: {_in: $collectionIds}, global_debt_part: {_gt: 0}},
    distinct_on: [collection_id]
  ) {
    collectionId: collection_id
    transactionTimestamp: transaction_timestamp
    transactionVersion: transaction_version
    borrowBase: borrow_base
    borrowElastic: borrow_elastic,
    globalDebt: vault_collection_debt_store_datas {
      debtBase: debt_base
      debtElastic: debt_elastic
      objectAddress: object_address
  	}
  }
}
